name: Weekly Actions Update Check

on:
  push

jobs:
  check-updates:
    env: 
      GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g actions-up
      # - run: npx actions-up 

      - name: Update workflow actions (SHA pinning)
        run: |
          set +e
          if [ -d ".github/workflows" ]; then
            echo "Running actions-up with SHA pinning"
            npx actions-up -y || true
          else
            echo "No workflows found, skipping"
          fi

      - name: Commit and push changes using PAT
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PAT1 }}
        run: |
          git config user.name "Krish Tambe"
          git config user.email "krishtambe@users.noreply.github.com"

          if git status --porcelain | grep .; then
            git add .github/workflows
            git commit -m "chore: update GitHub Actions versions"

            git remote add auth-origin https://${GITHUB_TOKEN}@github.com/krishtambe/actionsup.git
            git push auth-origin main
          else
            echo "No changes to commit" 
          fi 